spring.application.name=payment-service
server.port=8081
mercadopago.access-token=${MERCADOPAGO_TOKEN:token-ficticio-para-testes}
webhook.base-url=${WEBHOOK_URL:http://localhost:8081}
main-backend.url=${MAIN_BACKEND_URL:http://localhost:8080}