name: CI Pipeline - Payment Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name:  Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Validar configuração
        run: java -version

      - name: Validar configuração
        run: java -version

      - name: Rodar Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dar permissão de execução ao Maven Wrapper
        run: chmod +x ./mvnw

      - name: Instalar dependências e Executar Linter (Checkstyle)
        run: ./mvnw checkstyle:checkstyle

      - name: Executar Testes Unitários e Cobertura (Jacoco)
        run: ./mvnw test

      - name: Executar Testes Unitários e Cobertura (Jacoco)
        env:
          MERCADOPAGO_TOKEN: ${{ secrets.MERCADOPAGO_TOKEN }}
          WEBHOOK_URL: ${{ vars.WEBHOOK_URL }}
          MAIN_BACKEND_URL: ${{ vars.MAIN_BACKEND_URL }}
        run: ./mvnw test